### ISSUE TITLE
Support box-decoration-break: clone;

### ISSUE THREAD

**Issue by johannesodland** [adobe/balance-text#140]

**Comment by redmunds** [comment]
@johannesodland Sorry, I missed the notification when this issue was opened.

Currently, balance-text only works on block-level text elements. Handling `box-decoration-break` would only apply in the case where it's applied directly to block-level text elements. While that's valid and renderers need to handle that case, I can't think of a common use case for that, so there's currently no plan to support `box-decoration-break`. If you can find an example with a compelling use case, you may be able to change my mind.

As always, you're welcome to submit a pull request that implements this feature.
